baseURL = "https://kottn.github.io/mypage/"
languageCode = "ja"
title = "kottn's note"
theme = "temple"
# copyright = "(c) 2017 - 2018"

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "2017-2018 Takuma Kotani."
  github = "kottn"
  twitter = "kottn_jp"
